// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'model_propertyList.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Property _$PropertyFromJson(Map<String, dynamic> json) => Property(
      id: json['id'] as int?,
      landOnwerId: json['landOnwerId'] as int?,
      ownerid: json['ownerid'] as String?,
      propertyName: json['propertyName'] as String?,
      propertyDescription: json['propertyDescription'] as String?,
      area: json['area'] as String?,
      livingroom: json['livingroom'] as String?,
      livDescription: json['livDescription'] as String?,
      bedroom: json['bedroom'] as String?,
      bedDescription: json['bedDescription'] as String?,
      kitchen: json['kitchen'] as String?,
      kitDescription: json['kitDescription'] as String?,
      washroom: json['washroom'] as String?,
      washDescription: json['washDescription'] as String?,
      pool: json['pool'] as String?,
      poolDescription: json['poolDescription'] as String?,
      price: json['price'] as String?,
      discountedPrice: json['discounted_price'] as String?,
      timeline: json['timeline'] as String?,
      discount: json['discount'] as String?,
      pricepernight: json['pricepernight'] as String?,
      discountedPricepernight: json['discounted_pricepernight'] as String?,
      totalPrice: json['total_price'] as String?,
      totalDiscountedPrice: json['total_discounted_price'] as String?,
      serviceFee: json['service_fee'] as String?,
      state: json['state'] as String?,
      city: json['city'] as String?,
      longitude: (json['longitude'] as num?)?.toDouble(),
      latitude: (json['latitude'] as num?)?.toDouble(),
      propertyType: json['propertyType'] as String?,
      tenentType: json['tenentType'] as String?,
      terms: json['terms'] as String?,
      cancellationPolicy: json['cancellationPolicy'] as String?,
      avgRating: json['avgRating'] as String?,
      wishlist: json['wishlist'] as bool?,
      reviewed: json['reviewed'] as bool?,
      images:
          (json['images'] as List<dynamic>?)?.map((e) => e as String).toList(),
      reviews: (json['reviews'] as List<dynamic>?)
          ?.map((e) => ReviewModel.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

Map<String, dynamic> _$PropertyToJson(Property instance) => <String, dynamic>{
      'id': instance.id,
      'landOnwerId': instance.landOnwerId,
      'ownerid': instance.ownerid,
      'propertyName': instance.propertyName,
      'propertyDescription': instance.propertyDescription,
      'area': instance.area,
      'livingroom': instance.livingroom,
      'livDescription': instance.livDescription,
      'bedroom': instance.bedroom,
      'bedDescription': instance.bedDescription,
      'kitchen': instance.kitchen,
      'kitDescription': instance.kitDescription,
      'washroom': instance.washroom,
      'washDescription': instance.washDescription,
      'pool': instance.pool,
      'poolDescription': instance.poolDescription,
      'price': instance.price,
      'discounted_price': instance.discountedPrice,
      'timeline': instance.timeline,
      'discount': instance.discount,
      'pricepernight': instance.pricepernight,
      'discounted_pricepernight': instance.discountedPricepernight,
      'total_price': instance.totalPrice,
      'total_discounted_price': instance.totalDiscountedPrice,
      'service_fee': instance.serviceFee,
      'state': instance.state,
      'city': instance.city,
      'longitude': instance.longitude,
      'latitude': instance.latitude,
      'propertyType': instance.propertyType,
      'tenentType': instance.tenentType,
      'terms': instance.terms,
      'cancellationPolicy': instance.cancellationPolicy,
      'avgRating': instance.avgRating,
      'wishlist': instance.wishlist,
      'reviewed': instance.reviewed,
      'images': instance.images,
      'reviews': instance.reviews,
    };
