// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }



  static const Map<String,dynamic> ku = {

    "service_fee_wallet":" نرخی خزمەتگوزاری پێشوەختە لە ڕێگەی ژمارە موبایل یان جزدانەوە دەدرێت",
    "kindly_transfer_the_service_fee_to_one_of_the_below_numbers_through_the_provide_wallets_for_swift_booking_approval": "تکایە تەنها کرێی خزمەتگوزارییەکە بنێرە بۆ یەکێک لەم ژمارانەی خوارەوە  بۆ پەسەندکردنی حجزەکەت",
    "privacy_policy": "سياسەتی پاراستنی نهێنی",

    "new_reviews": "پێداچوونەوەکان",

    "property_name": "ناوی موڵک",
    "property_description": "%@وەسفکردنی موڵک",
    "review_text": "پێداچوونەوە",
    "discover_book_and_experience_daily_stays_effortlessly": "بیدۆزەرەوە، حجز بکە و ئەزموونی مانەوەی ڕۆژانە بەبێ ماندوو بوون بکە",
    "travel_made_simple_moments_made_special_find_unique_stays_with_us": "سەفەرکردن ئاسان کرا، ساتەکان تایبەت کرا لەگەڵ ئێمە شوێنی مانەوەی ناوازە بدۆزەرەوە",
    "make_your_trip_unforgettable_Smooth_stays_and_great_memories!": "بە مانەوەت لە سروشتی ئارام و یادگاری نایاب گەشتەکەت بکە بە یادگاریەكی لەبیرنەکراو ",
    "experience_Kurdistans_charm_in_our_cozy_homes_!": "ئەزموونی جوانی سروشتی كوردستان بكە",
    "filled_with_warm_hospitality_and_cultural_pride_Your_stay_promises_magic_and_true_beauty": "كە پڕە لە میوانداری گەرم و شانازی كەلتوری، بەڵێنی سحر و جوانی ڕاستەقینەت پێدەدەین بە مانەوەت لە ناو ماڵە ئارامەكانمام. ",
    "feel_at_home_in_any_place": "هەست بە بوون لە ماڵەوە بکە لە هەر شوێنێک",
    "we_got_a_cozy_place_waiting_for_you_no_matter_where_your_adventures_take_you": "ئێمە چاوەڕێی ئێوەین ، گرنگ نییە هەنگاو و ئارەزوەكانت  بەرەو كوێت ببەن , لە هەموو شوێنێك باشترینەكانمان بۆ ئامادە كردوون",
    "next": "دواتر",
    "search": "گەڕان",
    "filter": "فلتەر",
    "favourites": "دڵخوازەکان",

    "tourist_places": "شوێنی گەشتیاری",
    "register": "تۆمارکردن",
    "your_destination?": "؟ شوێنی مەبەستت",
    "choose_a_property": "موڵکێک هەڵبژێرە",
    "daily": "ڕۆژانە",
    "weekly": "هەفتانە",
    "monthly": "مانگانە",
    "january": "کانونی دووەم",
    "February": "فبراير",
    "march": "ئازار",
    "april": "نیسان",
    "may": "ئایار",
    "june": "حوزەیران",
    "july": "تەموز",
    "august": "ئاب",
    "september": "ئەیلول",
    "october": "تشرینی یەکەم",
    "november": "تشرینی دووەم",
    "december": "کانون یەکەم",
    "price": "نرخ",
    "offers": "داشکاندن",
    "rating": "پۆلێنکردن",
    "description": "پوختە",
    "reviews": "پێداچوونەوەکان",
    "map": "نەخشە",
    "select": "هەڵبژێرە",
    "book": "حجز بکە",
    "for_singles": "بۆ سینگڵەکان",
    "for_families": "بۆ خێزانەکان",
    "check_in_date": "بەرواری هاتنە ژوورەوە",
    "check_out_date": "بەرواری دەرچوون",
    "facilities": "وردەکاریەکان",
    "living_Room": "ژوری دانیشتن",
    "bed_Room": "ژووری نوستن",
    "kitchen": "چێشتخانە",
    "pool": "مەلەوانگە",
    "washroom": "گەرماو",
    "overview": "کورتە",
    "have_a_question?": "پرسیارێکتان هەیە؟",
    "ask_the_host": "لە خاوەن بپرسە",
    "book_Now": "ئێستا حجز بکە",
    "what_did_property_guests_say": "میوانانی موڵک چیان گوتیە",
    "rate_us!": "هەڵسەنگاندنمان بۆ بکەن!",
    "approximate_location": "شوێنی نزیکەیی",
    "view_on_map": "بینین لەسەر نەخشە",
    "property_terms": "مەرجەکان",
    "cancelation_and_postponement_policy": "یاساکانی هەڵوەشاندنەوە و داخستنی",
    "home": "سەرەکی",
    "wishlist": "دڵخوازەکان",
    "messages": "نامەکان",
    "hello": "سڵاو",
    "profile": "هەژمار",
    "booking": "حجز کردن",
    "notifications": "ئاگادارکردنەوەکان",
    "change_language": "گۆڕینی زمان",
    "fAQ": "پرسیارە بەردەوامەکان",
    "terms_of_use": "مەرجەکانی بەکارهێنان",
    "contact_us": "پەیوەندیمان پێوەبکە",
    "logout": "چوونە دەرەوە",
    "Begin_Your_Hosting_Journey_Do": "گەشتی میوانکردن دەست پێ بکە ئایا خانۆی گەشتیاری ،ڤیلا، مەزرەعە مۆتێل، کەرەڤان، هۆتێل تان هەیە؟لەگەڵ ئێمە میوانداری بکە، داهاتی زیادە بەدەستبهێنە ",


    "dukan": "دوکان",
    "akre": "ئاکرێ",
    "Akre": "ئاکرێ",
    "amedi": "ئامێدی",
    "Amedi": "ئامێدی",
    "zakho": "زاخۆ",
    "Zakho": "زاخۆ",
    "choman": "چۆمان",
    "dohuk": "دهۆ ک",
    "Dohuk": "دهۆ ک",
    "halabja": "هەڵەبچە",
    "hawler": "هەولێر",
    "sulaimanyah": "سلێمانی",
    "shaqlawa": " شەقڵاوە",
    "Shaqlawa": " شەقڵاوە",
    "soran": "سوڕان",
    "Soran": "سوڕان",
    "resort Houses": "خانۆی گەشتیاری",
    "farm Houses": "مەزرەعە",
    "cravans & Kepr": "کەپر و کەرەڤان",
    "motel & Apartments": "موتێل و شۆقەی تایبەت",
    "Motel & Apartments": "موتێل و شۆقەی تایبەت",
    "hotel": "هوتێل",









    "browse_pics_to_upload": "گەڕان بەدوای وێنەکان",

    "property_details": " وردەکارییەکانی موڵکەکەت",

    "posted_Properties": "موڵکەکانی پۆست کراو ",
    "total_bookings": "کۆی گشتی حجزەکان",
    "total_earning": "کۆی داهات",
    "average_rating": "تێکڕای هەڵسەنگاندن",
    "enter_Property_Name": "ناوی موڵکەکە دابنێ",
    "what_makes_your_property_unique?": "چی وايکردووە موڵکەکەت تايبەت بێت ؟",
    "describe_your_property": "وەسفی موڵکت بکە",
    "area_of_your_property": "بەمەتر(ڕووبەری موڵکەکەت)",
    "living_room": "هۆڵ",
    "bed_Rooms": "ژووری نوستن",
    "describe_your_Bed_Rooms": "باسی ژووری نوستنەکانت بکە",
    "describe_your_Kitchen": "باسی چێ شتخانەکەت بک ە",
    "describe_your_Washroom": "باسی گەرماوەکان بکە",
    "describe_your_pool": "باسی مەلەوانگە بکە",
    "images": "وێنە",
    "add_photos": "وێنە زياد بکە",
    "landlord_ID": "ناسنامەی خاوەن مۆڵک ",
    "where_is_located": "لە کوێيە",
    "full_address": "ناونیشانی تەواو",
    "latidude_and_longidude": "پانی و درێژی",
    "property_Type": "جۆری موڵک",
    "rent_type": "جۆری کرێ",
    "tenant_type": "جۆری کرێچی",
    "price_(IQD)": "السعر_(دينار عراقي)",
    "phone_no": "ژمارەی تەلەفۆن",
    "failed_to_add_property": "سەرکەوتوو نەبوی لە زیادکردنی موڵک",
    "sign_up": "خۆت تۆمار بکە",
    "sign_in": "چوونە ژوورەوە",
    "login_to_your_account": "چوونەژوورەوە بۆ ئەژمێرەکەت",
    "email": "ئیمەیڵ",
    "password": "پاسۆرد",
    "forget_your_password?": "پاسۆوردەکەت لەبیرچووە؟",
    "email_is_required": "ئیمەیڵ پێویستە",
    "wrong_password(when_entering_wrong_password_errors)": "پاسۆوردەکەت هەڵەیە",
    "do_not_have_an_account?": "هەژمارت نییە؟",
    "select_which_contact_details_should_we_use_to_reset_your_password": "ئەم ڕێگایەی خوارەوە هەڵبژێرە بۆ گوڕینی وشەی نهێنیەکەت",
    "via_Email": "لە ڕێگەی ئیمەیڵەوە",
    "via_SMS": "لە ڕێگەی نامە",
    "OTP_verification": "پشتڕاستکردنەوەی OTP",
    "code_has_been_sent_to:": "کۆدەکە نێردرا بۆ:",
    "verify": "پشتڕاست بکەرەوە",
    "resend": "دووبارە ناردنەوە",
    "create_new_account": "ئەکاونتی نوێ دروست بکە",
    "full_Name": "ناوى تەواو",
    "i_agree_with_terms_and_privacy": "ڕازیم بە مەرجەکان و تایبەتمەندییەکانم",
    "already_have_an_account": "پێشتر خۆت تۆمار کردووە",
    "Sulaymaniah": "سلێمانی",
    "sulaymaniah": "سلێمانی",




    "settings": "ڕێکخستن",
    "more": "زياتر",
    "full_name_is_required": "ناوی تەواوت پێويستە ",
    "password_is_required": "پاسۆوردەکەت پێويستە",
    "please_accept_the_terms_and_conditions": "تکايە مە رج و ڕێساکان قبوڵ بکە",
    "oTP_sent_successfully": " OTP بە سەرکەوتوويی نێردرا بۆ ئیمێلت",
    "privacy policy": "سياسەتی پاراستنی نهێنی",
    "tourist_Places": "شوێنی گەشتیاری",
    "my_Properties": "موڵکەکانی من",
    "hello_Landlord": "سڵاو خاوەن مۆڵک",
    "host_with_us": "لەگەڵ ئێمە میوانداری بکە",
    "travel_to_cities": "گەشت بۆ شارەکان",
    "search_by_Cities": "گەڕان بەپێی شار",
    "quick_contact": "پەیوەندی خێرا",
    "chat": "نامە",
    "email_us": "ئیمەیڵمان بۆ بنێرە",
    "enter_your_message_here": "لێرەدا نامەکەت بنووسە",
    "send": "ناردن",
    "name_is_required": "ناو پێویستە",
    "emalid email is required": "ئیمەیڵی دروست پێویستە",
    "message is required": "نامە پێویستە",
    "query_sent_successfully": "پرسیارەکە بە سەرکەوتوویی نێردراوە.",
    "payment_Successful ": "پارەدان سەرکەوتوو بوو",
    "booking_Successful": "حجز کردن سەرکەوتوو بوو",
    "past": "ڕابردوو",
    "upcoming": "لە داهاتوودا",
    "booking_id": "ناسنامەت بۆ حجزکردن",
    "pending": "لە چاوەڕوانیدا",
    "update": "نوێکردنەوە",
    "iD_Proof": "سەلماندنی ناسنامە",
    "favorites": "دڵخوازەکان",
    "sq._feet": "پێی دووجا",
    "submit": "ناردن ",
    "wrong_Password": "پاسۆردەکەت هەڵەیە",
    "login_Successful": "چوونەژوورەوە سەرکەوتوو بوو",
    "post_Property": "موڵکێک پۆست بکە",
    "begin_Your_Hosting_Journey": "گەشتی میوانداریکردنت دەست پێ بکە",
    "add_Property_Details": "وردەکارییەکانی موڵکەکەت زیاد بکە",
    "in_meters": "بە مەتر",
    "meter": "٢م",
    "select_number_of_available_rooms": "ژمارەی ژوورەکانی بەردەست هەڵبژێرە",
    "describe_Your_Living_rooms": "باسی ژووری میوانەکانت بکە",
    "select_number_of_Kitchen": "ژمارەی چێشتخانەکان هەڵبژێرە",
    "select_the_tentant_type": "جۆری کرێچی هەڵبژێرە",
    "smoking_type": "جۆری جگەرەکێشان",
    "select_Smoking_type": "جۆری جگەرەکێشان هەڵبژێرە",
    "select_the_smoking_type": "جۆری جگەرەکێشان هەڵبژێرە",
    "add_manually_The_Terms_and_Conditions": " مەرج و ڕێساکان تۆ زیاد بکە",
    "add_manually_Cancellation_Policy": "سیاسەتی هەڵوەشاندنەوە تۆ زیاد بکە",
    "select_the_terms_and_conditions_or_type_it": "مەرج و ڕێساکان هەڵبژێرە یان بینووسە",
    "failed_to_add_business": " شکستت هێنا لە زیادکردنی موڵکەکە",
    "last_seen_on": "دوایین جار بینراوە لە",
    "type_Something": "شتێک بنووسە",
    "mark_unavailable": " بەردەست نییە ئێستا",
    "update_Price": "گۆڕینی نرخ",
    "property_price_updated_successfully": "نرخی موڵک بە سەرکەوتوویی گۆڕدرا",
    "property_price_is_required": "نرخی موڵک پێویستە",






    "property_name_is_required": "ناوی موڵکەکە پێویستە",
    "property_Description_is_required": "وەسفکردنی موڵکەکە پێویستە",
    "area_of_property_is_required": "ڕووبەری موڵک پێویستە",
    "at_least_one_image_is_required": "لانی کەم یەک وێنە پێویستە",
    "add_Location_and_Terms": "شوێن و مەرجەکان زیاد بکە",
    "select_city": "شارەکە هەڵبژێرە",
    "select_the_rent_type": "جۆری کرێ هەڵبژێرە",
    "select_the_property_type":" جۆری موڵکەکەت هەڵبژێرە ",
    "Property_Sent_for_approval_Successfully":" موڵکەکەت بە سەرکەوتوویی نێردرا بۆ پەسەندکردن",
    "Property_Details":"وردەکارییەکانی موڵک",








    "app_title": "ناوی ئەپەکە",
    "experience_Kurdistan's_charm_in_our_cozy_homes_!": "ئەزموونی جوانی سروشتی كوردستان بكە",
    "filled_with_warm_hospitality_and_cultural_pride_Your_stay_promises_magic_and_true_beauty!": "كە پڕە لە میوانداری گەرم و شانازی كەلتوری  بەڵێنی سحر و جوانی ڕاستەقینەت پێدەدەین بە مانەوەت لە ناو ماڵە ئارامەكانمام. ",
    "feel_at_home_in_any_place.": "هەست بە بوون لە ماڵەوە بکە لە هەر شوێنێک",
    "we've_got_a_cozy_place_waiting_for_you,_no_matter_where_your_adventures_take_you!": "ئێمە چاوەڕێی ئێوەین، گرنگ نییە هەنگاو و ئارەزوەكانت  بەرەو كوێت ببەن , لە هەموو شوێنێك باشترینەكانمان بۆ ئامادە كردوون",
    "area_of_your_property_(in meter)": "بە مەتر) ڕووبەری موڵکەکەت)",
    "email_is_required_(when_entering_wrong_email_errors)": "ئیمەیڵ پێویستە",


    "emalid_email_is_required": "ئیمەیڵی دروست پێویستە",
    "message_is_required": "نامە پێویستە",
    "query_sent_successfully.": "پرسیارەکە بە سەرکەوتوویی نێردرا.",

    "amount_Paid": "بڕی دراو",
    "booking_date": "بەرواری حجز کردن",
    "resort_Houses": "خانووی گەشتیاری",
    "caraven_&_Kepr": "کەرەڤان و کەپر",
    "farm_House": "مەزرەعە",
    "motel_&_Private_Flats": "موتێل و شوقەی تایبەت",
    "booking_Details_not_found": "وردەکاری حجزکردن نەدۆزرایەوە",
    "apartment": "شوقە",
    "night": "شەو",
    "unit_code": "کۆدی یەکە",
    "for_Singles_": "بۆ سینگڵەکان",
    "choose_language": "زمان هەڵبژێرە",
    "write_Review": "سەرنجەکانتان بنووسن",
    "describe_Your_Experience": "ئەزموونی خۆت باس بکە",
    "post": "ناردن",
    "checkout": "دەرچوون",
    "select_number_of_Pools":  "گەڕان بەدوای وێنەکان ",
    "reservation_Details": "وردەکاری حجز کردن",
    "sub_Total": "پێش- کۆی گشتی ",
    "service_Fee": "کرێی خزمەتگوزاری",
    "total": "کۆی گشتی",
    "payment_method": "شێوازی پارەدان",
    "cash": "پارەی کاش",
    "wallets": "جزدان",
    "payment_Procedure": "ڕێکارەکانی پارەدان",
    "book_Property": "موڵکێک حجز بکە",
    "property_Booked,_Please_wait_for_admin_approval": "موڵکەکە حجز کرابن",
    "booking_Done": "حجز کردن ئەنجام درا",
    "booking_sent_for_approval_successfully": "حجزکردن نێردرا بۆ پەسەندکردن",
    "your_payment_for_booking_property_is_successfully_done._Please_wait_for_booking_confirmation.": "پارەدانەکەت بۆ حجزکردنی موڵک بە سەرکەوتوویی ئەنجامدرا. تکایە چاوەڕێی پشتڕاستکردنەوەی حجز کردن بن.",
    "your_property_booking_is_successfully_confirmed_by_administration.": "حجزکردنەکە بە سەرکەوتوویی لەلایەن ئەدمینەوە پشتڕاست کراوە",
    "we're_here_to_help you_with_anything_and_everything_on_Gasht": "ئێمە لێرەین بۆ ئەوەی یارمەتیت بدەین لە هەر شتێک و هەموو شتێک لەسەر Gasht",
    "by_your_use_of_this_app,_you_confirm_your_acceptance_and_it_would_be_accepted_as_would_a_written agreement_would_a_written_agreement": "بە بەکارهێنانی ئەم ئەپە، قبوڵکردنەکەت پشتڕاست دەکەیتەوە و وەرگیرا وەک ڕێککەوتنێکی نوسراو ڕێککەوتنێکی نوسراو وەردەگیرێت",
    "arabic": "عەرەبی",
    "kurdish": "کوردی",
    "select_Number_of_washroom": "ژمارەی گەرماوەکان هەڵبژێرە",
    "booking_Detail": "وردەکاری حجزکردن",
    "booked": "حجزکرا",
    "booking_Date": "بەرواری حجزکردن",
    "booking_ID ": "ناسنامەی حجزکردن",
    "daily_quote": "وتەی ڕۆژانە",
    "oK": "باشە",
    "numeric_price": "نرخ دەبێت بە ژمارە بێت",


    "Otp_verified":"  کودەکە بە سەرکەوتوویی پشتڕاستکرایەوە",
    "Create_Password":"پاسۆوردێک دروستبکە",
    "Create_your_new_password":"پاسۆوردێکی نوێ دروست بکە",
    "Confirm_Password":"پاسۆوردەکە پشتڕاست بکەرەوە",
    "Password_length_short":"پاسۆوردەکە کورتە",
    "Confirm_Password_is_required":"پاسۆورد پشتڕاستکردنەوە پێویستە  ",
    "both_Passwords_are_different":"هەردوو پاسۆوردەکە جیاوازن",
    "password_Changed_Successfully":"پاسۆورد بە سەرکەوتوویی گۆڕدرا",


    "rate_this_Property":"هەڵسەنگاندن بۆ موڵکەکە بکە",
    "Already Reviewed":"پێشتر پێداچوونەوەی بۆ کراوە",
    "Review_submitted_successfully":"پێداچوونەوە بە سەرکەوتوویی پێشکەش کرا",
    "Profile_Updated_Successfully":"پڕۆفایل بە سەرکەوتوویی نوێکرایەوە",
    "listing": "ليست",
    "discover-tranquility" : "جوانى و ئارامی لە شوێنە گەشتیاریەکان بیدۆزەرەوە."

















  }


  ;
  static const Map<String,dynamic> en ={
    "kindly_transfer_the_service_fee_to_one_of_the_below_numbers_through_the_provide_wallets_for_swift_booking_approval": "Kindly transfer the service fee to one of the below numbers through the provide wallets for swift booking approval",
    "app_title": "My App",
    "explore": "Explore",
    "property_name": "Property Name",
    "property_description": "Property Description%@",
    "review_text": "Review Text",
    "discover_book_and_experience_daily_stays_effortlessly": "Discover, book, and experience daily stays effortlessly.",
    "travel_made_simple_moments_made_special_find_unique_stays_with_us": "Travel made simple moments made special find unique stays with us.",
    "make_your_trip_unforgettable_Smooth_stays_and_great_memories!": "Make your trip unforgettable Smooth stays and great memories!",
    "experience_Kurdistans_charm_in_our_cozy_homes_!": "Experience Kurdistan's charm in our cozy homes !",
    "filled_with_warm_hospitality_and_cultural_pride_Your_stay_promises_magic_and_true_beauty": "Filled with warm hospitality and cultural pride. Your stay promises magic and true beauty!",
    "feel_at_home_in_any_place": "Feel at home in any place.",
    "we_got_a_cozy_place_waiting_for_you_no_matter_where_your_adventures_take_you": "We've got a cozy place waiting for you, no matter where your adventures take you!",
    "next": "NEXT",
    "search": "Search",
    "filter": "Filter",
    "tourist_places": "Tourist places",
    "register": "Register",
    "your_destination?": "Your destination?",
    "choose_a_property": "Choose a property",
    "daily": "Daily",
    "weekly": "Weekly",
    "monthly": "Monthly",
    "numeric_price": "Price must be in Numeric Value",
    "january": "January",
    "february": "February",
    "march": "March",
    "april": "April",
    "may": "May",
    "june": "June",
    "july": "July",
    "august": "August",
    "september": "September",
    "october": "October",
    "november": "November",
    "december": "December",
    "price": "Price",
    "offers": "Offers",
    "rating": "Rating",
    "description": "Description",
    "reviews ": "Reviews ",
    "new_reviews":"Reviews",
    "map": "Map",
    "select": "Select",
    "book": "Book",
    "for_singles": "For singles",
    "for_families": "For families",
    "check_in_date": "Check-in date",
    "check_out_date": "Check-out date",
    "facilities": "Facilities",
    "living_Room": "Living Room",
    "bed_Room": "Bed Room ",
    "kitchen": "Kitchen",
    "pool": "Pool",
    "washroom": "Washroom",
    "overview": "Overview",
    "have_a_question?": "Have a question?",
    "ask_the_host": "Ask the host",
    "book_Now": "Book Now",
    "what_did_property_guests_say": "What did property guests say",
    "rate_us!": "Rate us!",
    "approximate_location": "Approximate location",
    "view_on_map": "View on map",
    "property_terms": "Property Terms",
    "new_terms": "Property Terms",
    "cancelation_and_postponement_policy": "Cancellation and postponement policy",
    "home": "Home",
    "wishlist": "Wishlist",
    "messages": "Messages",
    "more": "More",
    "hello": "Hello",
    "profile": "Profile",
    "booking": "Booking",
    "notifications": "Notifications",
    "change_language": "Change Language",
    "fAQ": "FAQ",
    "terms_of_use": "Terms of use",
    "contact_us": "Contact us",
    "logout": "Logout",
    "Begin_Your_Hosting_Journey_Do": "Begin Your Hosting Journey Do you have Tourist house, Villa, Farmhouse Motel, Caravans, Hotel Host with us, earn extra income",

    "posted_Properties": "Posted Properties",
    "total_bookings": "Total bookings",
    "total_earning": "Total earning",
    "average_rating": "Average rating",
    "enter_Property_Name": "Enter Property Name",
    "what_makes_your_property_unique?": "What makes your property unique?",
    "describe_your_property": "Describe your property",
    "area_of_your_property": "Area of your property (in meter)",
    "living_room": "living room",
    "bed_Rooms": "Bed Rooms",
    "describe_your_Bed_Rooms": "Describe your Bed Rooms",
    "describe_your_Kitchen": "Describe your Kitchen",
    "describe_your_Washroom": "Describe your Washroom",
    "describe_your_pool": "Describe your pool",
    "images": "Images",
    "add_photos": "Add photos",
    "landlord_ID": "Landlord ID",
    "where_is_located": "Where is located",
    "full_address": "full address",
    "latidude_and_longidude": "Latitude and Longitude",
    "property_Type": "Property Type",
    "rent_type": "Rent type",
    "tenant_type": "Tenant type",
    "price_(IQD)": "Price (IQD)",
    "phone_no": "Phone no",
    "failed_to_add_property": "Failed to add property",
    "sign_up": "Sign up",
    "sign_in": "Sign in",
    "login_to_your_account":"Login to your account",
    "email": "Email",
    "password": "Password",
    "forget_your_password?": "Forget your password?",
    "email_is_required_(when_entering_wrong_email_errors)": "Email is required (when entering wrong email errors)",
    "wrong_password(when_entering_wrong_password_errors)": "Wrong password (when entering wrong Password errors)",
    "do_not_have_an_account?": "Do not have an account?",
    "select_which_contact_details_should_we_use_to_reset_your_password": "Select which contact details should we use to reset your password",
    "via_Email": "Via Email",
    "via_SMS": "Via SMS",
    "oTP_verification": "OTP verification",
    "code_has_been_sent_to:": "Code has been sent to:",
    "verify": "Verify",
    "resend": "Resend",
    "create_new_account": "Create new account",
    "full_Name": "Full Name",
    "i_agree_with_terms_and_privacy": "I agree with terms and privacy",
    "already_have_an_account": "Already have an account",

    "settings": "Setting",
    "full_name_is_required": "Full name is required",
    "email_is_required":"Email is required",
    "valid_email_is_required": "Valid email is required",
    "password_is_required": "Password is required",
    "please_accept_the_terms_and_conditions": "Please accept the terms and conditions",
    "oTP_sent_successfully": "OTP sent successfully",
    "privacy_policy": "Privacy policy",
    "tourist_Places": "Tourist Places",
    "my_Properties": "My Properties",
    "hello_Landlord": "Hello Landlord",
    "host_with_us": "Host with us",
    "travel_to_cities": "Travel to cities",
    "search_by_Cities": "Search by Cities",
    "quick_contact": "Quick contact",
    "chat": "Chat",
    "email_us": "Email us",
    "enter_your_message_here": "Enter your message here.....",
    "send": "Send",
    "name_is_required": "Name is required",
    "email is required": "Email is required",
    "emalid email is required": "Valid email is required",
    "message_is_required": "Message is required",
    "query_sent_successfully": "Query sent successfully.",
    "payment_Successful": "Payment Successful ",
    "booking_Successful": "Booking Successful",
    "past": "Past",
    "upcoming": "Upcoming",
    "booking_id": "Booking id",
    "pending": "Pending",
    "update": "Update",
    "iD_Proof": "ID Proof",
    "favourites": "Favourites",
    "sq._feet": "sq. feet",
    "submit": "Submit",
    "wrong_Password": "Wrong Password",
    "login_Successful": "Login Successful",
    "post_Property": "Post Property",
    "begin_Your_Hosting_Journey": "Begin Your Hosting Journey",
    "add_Property_Details": "Add Property Details",
    "in_meters": "In meters",
    "select_number_of_available_rooms": "Select number of available rooms",
    "describe_Your_Living_rooms": "Describe Your Living rooms",
    "select_number_of_Kitchen": "Select number of Kitchen",
    "select_number_of_Pools": "Select number of Pools",
    "browse_pics_to_upload": "Browse pics to upload",

    "property_name_is_required": "Property name is required",
    "property_Description_is_required": "Property Description is required",
    "area_of_property_is_required": "Area of property is required",
    "at_least_one_image_is_required": "At least one image is required",
    "add_Location_and_Terms": "Add Location and Terms",
    "select_city": "Select city",
    "select_the_rent_type": "Select the rent type",
    "select_the_property_type": "Select the property type",
    "Property_Sent_for_approval_Successfully":"Property Sent for approval Successfully",

    "meter": "m²",
    "rate_this_Property":"Rate this Property",
    "Already Reviewed":"Already Reviewed",
    "Review_submitted_successfully":"Review submitted successfully",
    "Profile_Updated_Successfully":"Profile Updated Successfully",





    "select_the_tentant_type": "Select the tenant type",
    "smoking_type": "Smoking type",
    "select_Smoking_type": "Select Smoking type",
    "select_the_smoking_type": "Select the smoking type",
    "add_manually_The_Terms_and_Conditions": "Add manually The Terms and Conditions",
    "add_manually_Cancellation_Policy": "Add manually Cancellation Policy",
    "select_the_terms_and_conditions_or_type_it": "Select the terms and conditions or type it",
    "failed_to_add_business": "Failed to add business",
    "last_seen_on": "Last seen on",
    "type_Something": "Type Something",
    "mark_unavailable": "Mark unavailable",
    "update_Price": "Update Price",
    "property_price_updated_successfully": "Property price updated successfully",
    "property_price_is_required": "Property price is required",
    "property_details": "Property Details",

    "service_fee_wallet":"Service fee is to be paid in advance through wallet",


    "otp_verified":"OTP verified Successfully",
    "password_Changed_Successfully":"Password Changed Successfully",
    "both_Passwords_are_different":"Both Passwords are different",
    "Create_Password":"Create Password",
    "Confirm_Password":"Confirm Password",
    "Create_your_new_password":"Create your new password",
    "Password_length_short":"Password length is short",
    "Confirm_Password_is_required":"Confirm Password is required",
    "service_fee_advance":"Service fee is to be paid in advance through wallet",



    "experience_Kurdistan's_charm_in_our_cozy_homes_!": "Experience Kurdistan's charm in our cozy homes !",
    "filled_with_warm_hospitality_and_cultural_pride_Your_stay_promises_magic_and_true_beauty!": "Filled with warm hospitality and cultural pride. Your stay promises magic and true beauty!",
    "feel_at_home_in_any_place.": "Feel at home in any place.",
    "we've_got_a_cozy_place_waiting_for_you,_no_matter_where_your_adventures_take_you!": "We've got a cozy place waiting for you, no matter where your adventures take you!",




    "area_of_your_property_(in meter)": "Area of your property (in meter)",

    "quick_contact ": "Quick contact",
    "Chat": "Chat",
    "emalid_email_is_required": "Valid email is required",
    "query_sent_successfully.": "Query sent successfully.",
    "payment_Successful ": "Payment Successful ",

    "amount_Paid": "Amount Paid",
    "booking_date": "Booking date",
    "resort_Houses": "Resort Houses",
    "caraven_&_Kepr": "Caravan & Kepr",
    "farm_House": "Farm House",
    "motel_&_Private_Flats": "Motel & Private Flats",
    "booking_Details_not_found": "Booking Details not found",
    "apartment": "Apartment",
    "night": "Night",
    "unit_code": "Unit code",
    "for_Singles_": "For Singles ",
    "choose_language": "Choose language",
    "write_Review": "Write Review",
    "describe_Your_Experience": "Describe Your Experience",
    "post": "Post",
    "checkout": "Checkout",
    "reservation_Details": "Reservation Details",
    "sub_Total": "Sub-Total",
    "service_Fee": "Service Fee",
    "total": "Total",
    "payment_method": "Payment method",
    "cash": "Cash",
    "wallets": "Wallets",
    "payment_Procedure": "Payment Procedure",
    "book_Property": "Book Property",
    "property_Booked,_Please_wait_for_admin_approval": "Property Booked, Please wait for admin approval",
    "booking_Done": "Booking Done",
    "booking_sent_for_approval_successfully": "Booking sent for approval successfully",
    "your_payment_for_booking_property_is_successfully_done._Please_wait_for_booking_confirmation.": "Your payment for booking property is successfully done. Please wait for booking confirmation.",
    "your_property_booking_is_successfully_confirmed_by_administration.": "Your property booking is successfully confirmed by administration.",
    "we're_here_to_help you_with_anything_and_everything_on_Gasht": "We're here to help you with anything and everything  on Gasht",
    "by_your_use_of_this_app,_you_confirm_your_acceptance_and_it_would_be_accepted_as_would_a_written agreement_would_a_written_agreement": "By your use of this app, you confirm your acceptance and it would be accepted as would a written agreement would a written agreement",
    "arabic": "Arabic",
    "kurdish": "Kurdish",
    "select_Number_of_washroom": "Select Number of washroom",
    "booking_Detail": "Booking Detail",
    "booked": "Booked",
    "booking_Date": "Booking Date",
    "booking_ID ": "Booking ID ",
    "daily_quote": "Daily quote",
    "oK": "OK",
    "dukan": "dukan",
    "akre": "Akre",
    "amedi": "Amedi",
    "zakho": "Zakho",
    "choman": "Choman",
    "dohuk": "Dohuk",
    "halabja": "Halabja",
    "hawler": "Hawler",
    "sulaimanyah": "Sulaimanyah",
    "shaqlawa": "Shaqlawa",
    "soran": "Soran",
    "resort Houses": "Resort Houses",
    "farm Houses": "Farm Houses",
    "cravans & Kepr": "Cravans & Kepr",
    "motel & Apartments": "Motel & Apartments",
    "hotel": "Hotel",
    "listing": "Listing",
    "discover-tranquility" : "Discover tranquility and luxury at resorts."

  }

  ;




  static const Map<String,dynamic> ar ={
    "kindly_transfer_the_service_fee_to_one_of_the_below_numbers_through_the_provide_wallets_for_swift_booking_approval": "يرجى تحويل رسوم الخدمة إلى أحد الأرقام أدناه من خلال المحافظ المخصصة للموافقة السريعة على الحجز",
    "privacy_policy": "سياسة الخصوصية",
    "app_title": "عنوان التطبيق",
    "numeric_price": "يجب أن يكون السعر بالقيمة الرقمية.",
    "hello": "مرحبا",
    "explore": "استكشف",
    "property_description": " @% وصف الملكية",
    "review_text": " المراجعة",
    "discover_book_and_experience_daily_stays_effortlessly": "اكتشف واحجز واستمتع بتجربة الإقامات اليومية بسهولة",
    "travel_made_simple_moments_made_special_find_unique_stays_with_us": "أصبح السفر بسيطًا، واللحظات أصبحت مميزة ابحث عن إقامات فريدة معنا",
    "make_your_trip_unforgettable_Smooth_stays_and_great_memories!": "اجعل رحلتك لا تنسى إقامات هادئة وذكريات رائعة",
    "experience_Kurdistans_charm_in_our_cozy_homes_!": "!أستمتع بسحر كردستان في منازلنا المريحة",
    "filled_with_warm_hospitality_and_cultural_pride_Your_stay_promises_magic_and_true_beauty": "المليئة بكرم الضيافة والفخر الثقافي إقامتك تبشر بالسحر والجمال الحقيقي.",
    "feel_at_home_in_any_place": "تشعر وكأنك في منزلك في أي مكان",
    "we_got_a_cozy_place_waiting_for_you_no_matter_where_your_adventures_take_you": "لدينا مكان مريح في انتظارك، بغض النظر عن المكان الذي تأخذك إليه مغامراتك!",
    "next": "التالي",
    "search": "ابحث",
    "filter": "فلتر",
    "tourist_places": "الاماكن السياحية",
    "register": "تسجیل",
    "your_destination?": "وجهتك؟",
    "choose_a_property": "اخترعقارًا",
    "daily": "يوميا",
    "weekly": "أسبوعي",
    "monthly": "شهريا",
    "january": "كانون الثاني",
    "february": " شباط",
    "march": "آذار",
    "april": "نيسان",
    "may": " أيار",
    "june": "حزيران",
    "july": "تموز",
    "august": "آب",
    "september": "أيلول",
    "october": " تشرين الأول",
    "november": "تشرين الثاني",
    "december": "كانون الاول",
    "price": "السعر",
    "offers": "العروض",
    "rating": "التقييم",
    "description": "المواصفات",
    "reviews": "المراجعات",
    "map": "خريطة",
    "select": "اختر",
    "book": "احجز",
    "new_reviews": "المراجعات",

    "for_singles": "للعزاب",
    "for_families": "للعائلات",
    "check_in_date": "تاريخ الدخول",
    "check_out_date": "تاريخ المغادرة",
    "facilities": "التفاصيل",
    "living_Room": "غرفة الجلوس",
    "bed_Room": "غرفة نوم",
    "kitchen": "المطبخ",
    "Sulaymaniah": "سليمانية",
    "sulaymaniah": "سليمانية",
    "pool": "حوض السباحة",
    "washroom": "الحمام",
    "overview": "ملخص",
    "have_a_question?": "لديك سؤال؟",
    "ask_the_host": "اسأل المضيف",
    "book_Now": "احجز الآن",
    "what_did_property_guests_say": "ماذا قال الضيوف عن المكان؟",
    "rate_us!": "قيمنا!",
    "approximate_location": "الموقع التقريبي",
    "view_on_map": "عرض على الخريطة",
    "property_terms": "شروط الملكية",
    "cancelation_and_postponement_policy": "سياسة الإلغاء أو التأجيل",
    "home": "الرئيسية",
    "wishlist": "المفضلة",
    "messages": "الرسائل",
    "profile": "حسابك",
    "booking": "الحجز",
    "notifications": "الإشعارات",
    "change_language": "تغيير اللغة",
    "fAQ": "الأسئلة الشائعة",
    "terms_of_use": "شروط الاستخدام",
    "contact_us": "اتصل بنا",
    "logout": "تسجيل خروج",
    "Begin_Your_Hosting_Journey_Do": "بدأ رحلة الاستضافة الخاصة بك هل لديك بيت سياحي، فيلا، مزرعة موتيل، كرفان، فندق؟استضف معنا واحصل على دخل إضافي",


    "meter": "٢م",


    "property_name": "اسم الملكية",
    "posted_Properties": "المالك المنشورة",
    "total_bookings": "إجمالي الحجوزات",
    "total_earning": "الأرباح الكلية",
    "average_rating": "معدل تقييم",
    "enter_Property_Name": "أدخل اسم الملكية",
    "what_makes_your_property_unique?": "ما الذي يجعل ملكك فريدة من نوعها؟",
    "describe_your_property": "قم بوصف ملكك",
    "area_of_your_property": "بالمتر) مساحة عقارك)",
    "living_room": "غرفة المعيشة",
    "bed_Rooms": "غرف النوم",
    "describe_your_Bed_Rooms": "قم بوصف غرف النوم",
    "describe_your_Kitchen": "قم بوصف مطبخك ",
    "describe_your_Washroom": "قم بوصف الحمام",
    "describe_your_pool": "وصف حوض السباحة",
    "images": "الصور",
    "add_photos": "أضف صور",
    "landlord_ID": "هوية المالك",
    "where_is_located": "اين يقع",
    "full_address": "العنوان الكامل",
    "latidude_and_longidude": "خط العرض وخط الطول",
    "property_Type": "نوع الملكية",
    "rent_type": "نوع الإيجار",
    "tenant_type": "نوع المستأجر",
    "price_(IQD)": "السعر(IQD)",
    "phone_no": "رقم الهاتف",
    "failed_to_add_property": "فشل في إضافة الملك",
    "sign_up": "قم بالتسجيل",
    "sign_in": "تسجيل الدخول",
    "login_to_your_account": "تسجيل الدخول إلى حسابك",
    "email": "بريد إلكتروني",
    "password": "كلمة السر",
    "forget_your_password?": "نسيت كلمة المرور؟",
    "email_is_required": "البريد الالكتروني مطلوب",
    "wrong_password": "كلمة مرور خاطئة",
    "do_not_have_an_account?": "لا تملك حساب؟",
    "select_which_contact_details_should_we_use_to_reset_your_password": "اختر تفاصيل الاتصال التي ينبغي أن نستخدمها لإعادة تعيين كلمة المرور الخاصة بك",
    "via_Email": "عبر البريد الالكتروني",
    "via_SMS": "عبر الرسالة",
    "oTP_verification": "التحقق من OTP",
    "code_has_been_sent_to:": "تم إرسال الرمز إلى:",
    "verify": "تحقق من",
    "resend": "إعادة إرسال",
    "create_new_account": "انشاء حساب جديد",
    "full_Name": "الاسم الكامل",
    "i_agree_with_terms_and_privacy": "أوافق على الشروط والخصوصية",
    "already_have_an_account": "هل لديك حساب",

    "browse_pics_to_upload": "تصفح الصور للتحميل",

    "settings": "ضبط",
    "more": "المزيد",
    "full_name_is_required": "االسم الكامل مطلوب",
    "password_is_required": "مطلوب كلمة السر",
    "please_accept_the_terms_and_conditions": "يرجى قبول الشروط والأحكام",
    "oTP_sent_successfully": "تم ارسال الكود بنجاح ",
    "privacy policy": "سياسة الخصوصية",
    "tourist_Places": "أماكن سياحية",
    "my_Properties": "ممتلكاتي",
    "hello_Landlord": "مرحبا",
    "host_with_us": "استضیف معنا",
    "travel_to_cities": "السفر إلى المدن",
    "search_by_Cities": "البحث حسب المدن",
    "quick_contact": "الاتصال السريع",
    "chat": "محادثة",
    "email_us": "راسلنا عبر البريد الإلكتروني",
    "enter_your_message_here": "أدخل رسالتك هنا",
    "send": "إرسال",
    "name_is_required": "الاسم مطلوب",
    "message_is_required": "الرسالة مطلوبة",
    "query_sent_successfully": "تم إرسال الاستفسار بنجاح.",
    "payment_Successful ": "تم الدفع بنجاح",
    "booking_Successful": "تم الحجز بنجاح",
    "past": "الماضي",
    "upcoming": "القادمة",
    "booking_id": "هوية الحجز",
    "pending": "قيد الإنتظار",
    "update": "تحديث",
    "iD_Proof": "إثبات الهوية",
    "favourites": "المفضلة",
    "sq._feet": "قدم مربع",
    "submit": "إرسال",
    "wrong_Password": "كلمة المرور خاطئة",
    "login_Successful": "تم تسجيل الدخول بنجاح",
    "post_Property": "نشر عقار",
    "begin_Your_Hosting_Journey": "ابدأ رحلتك في الاستضافة",
    "add_Property_Details": "إضافة تفاصيل الملكية",
    "in_meters": "بالمتر",
    "select_number_of_available_rooms": "اختر عدد الغرف المتاحة",
    "describe_Your_Living_rooms": "وصف غرف المعيشة الخاصة بك",
    "select_number_of_Kitchen": "اختر عدد المطابخ",
    "select_the_tentant_type": "حدد نوع المستأجر",
    "smoking_type": "نوع التدخين",
    "select_Smoking_type": "اختر نوع التدخين",
    "select_the_smoking_type": "اختر نوع التدخين",
    "add_manually_The_Terms_and_Conditions": "أضف الشروط والأحكام يدويًا",
    "add_manually_Cancellation_Policy": "أضف سياسة الإلغاء يدويًا",
    "select_the_terms_and_conditions_or_type_it": "حدد الشروط والأحكام أو اكتبها",
    "failed_to_add_business": "لقد فشلت في إضافة الملكية",
    "last_seen_on": "شوهد آخر مرة في",
    "type_Something": "اكتب شيئا",
    "mark_unavailable": "وضع علامة غير متاح حاليا",
    "update_Price": "تحديث السعر",
    "property_price_updated_successfully": "تم تحديث سعر بنجاح",
    "property_price_is_required": "مطلوب سعر الملكية",

    "property_details": "إضافة تفاصيل",


    "dukan": "دوکان",
    "akre": " عقرة",
    "Akre": " عقرة",
    "amedi": "عمادیة",
    "Amedi": "عمادیة",
    "zakho": "زاخو",
    "Zakho": "زاخو",
    "choman": "چومان",
    "dohuk": "دهوک",
    "Dohuk": "دهوک",
    "halabja": "حلبجة",
    "hawler": "اربیل",
    "sulaimanyah": "سلیمانیة",
    "shaqlawa": "شقلاوة",
    "Shaqlawa": "شقلاوة",
    "soran": "سوران",
    "Soran": "سوران",
    "resort Houses": "بیوت سیاحیة",
    "farm Houses": "مزرعة",
    "cravans & Kepr": " کرفان و کەبر",
    "motel & Apartments": "موتیل و شقق خاصة",
    "Motel & Apartments": "موتیل و شقق خاصة",
    "hotel": "فندق",


    "property_name_is_required": "اسم العقار مطلوب",
    "property_Description_is_required": "وصف العقار مطلوب",
    "area_of_property_is_required": "مطلوب مساحة العقار",
    "at_least_one_image_is_required": "مطلوب صورة واحدة على الأقل",
    "add_Location_and_Terms": "أضف الموقع والشروط",
    "select_city": "اختر مدينة",
    "select_the_rent_type": "اختر نوع الإيجار",
    "select_the_property_type":"اختر نوع العقار",
    "Property_Sent_for_approval_Successfully":"تم إرسال العقار للموافقة بنجاح ",



    "experience_Kurdistan's_charm_in_our_cozy_homes_!": "!أستمتع بسحر كردستان في منازلنا المريحة",
    "filled_with_warm_hospitality_and_cultural_pride_Your_stay_promises_magic_and_true_beauty!": "المليئة بكرم الضيافة والفخر الثقافي إقامتك تبشر بالسحر والجمال الحقيقي.",
    "feel_at_home_in_any_place.": "تشعر وكأنك في منزلك في أي مكان",
    "we've_got_a_cozy_place_waiting_for_you,_no_matter_where_your_adventures_take_you!": "لدينا مكان مريح في انتظارك، بغض النظر عن المكان الذي تأخذك إليه مغامراتك!",


    "email_is_required_(when_entering_wrong_email_errors)": "البريد الالكتروني مطلوب",
    "wrong_password(when_entering_wrong_password_errors)": "كلمة السر خاطئة",

    "quick_contact ": "الاتصال السريع",
    "emalid_email_is_required": "مطلوب البريد الإلكتروني الصحيح",
    "query_sent_successfully.": "تم إرسال الاستفسار بنجاح.",

    "amount_Paid": "المبلغ المدفوع",
    "booking_date": "تاريخ الحجز",
    "resort_Houses": "بيوت السياحية",
    "caraven_&_Kepr": "كرفان و کبر",
    "farm_House": "مزرعة",
    "motel_&_Private_Flats": "موتيل وشقق خاصة",
    "booking_Details_not_found": "لم يتم العثور على تفاصيل الحجز",
    "apartment": "شقة",
    "night": "ليلة",
    "unit_code": "كود الوحدة",
    "for_Singles_": "للعزاب",
    "choose_language": "اختر اللغة",
    "write_Review": "اكتب ملاحظاتك",
    "describe_Your_Experience": "قم بوصف تجربتك",
    "post": "انشر",
    "checkout": "الخروج",
    "select_number_of_Pools":  "تصفح الصور للتحميل",
    "reservation_Details": "تفاصيل الحجز",
    "sub_Total": "المجموع الفرعي",
    "service_Fee": "رسوم الخدمة",
    "total": "المجموع",
    "payment_method": "طريقة الدفع",
    "cash": "نقد",
    "wallets": "محفظة",
    "payment_Procedure": "إجراءات الدفع",
    "book_Property": "احجز عقارا",
    "property_Booked,_Please_wait_for_admin_approval": "تم حجز العقار، برجاء انتظار موافقة الادمن",
    "booking_Done": "تم الحجز",
    "booking_sent_for_approval_successfully": "تم إرسال الحجز للموافقة عليه",
    "your_payment_for_booking_property_is_successfully_done._Please_wait_for_booking_confirmation.": "تم الدفع لحجز العقار بنجاح. يرجى الانتظار لتأكيد الحجز.",
    "your_property_booking_is_successfully_confirmed_by_administration.": "تم تأكيد حجز مكان الإقامة الخاص بك بنجاح من قبل الادمن",
    "we're_here_to_help you_with_anything_and_everything_on_Gasht": "نحن هنا لمساعدتك في أي شيء وكل شيء في Gasht",
    "by_your_use_of_this_app,_you_confirm_your_acceptance_and_it_would_be_accepted_as_would_a_written agreement_would_a_written_agreement": "استخدامك لهذا التطبيق، فإنك تأكد موافقتك وسيتم قبوله كما هو الحال مع الاتفاقية المكتوبة",
    "arabic": "عربي",
    "kurdish": "كردي",
    "select_Number_of_washroom": "حدد عدد الحمامات",
    "booking_Detail": "تفاصيل الحجز",
    "booked": "حجزت",
    "booking_Date": "تاريخ الحجز",
    "booking_ID ": "معرف الحجز",
    "daily_quote": "الاقتباس اليومي",
    "oK": "موافق",

    "otp_verified":"تم التحقق من کلمة السر بنجاح",
    "Create_Password":"إنشاء كلمة السر",
    "Create_your_new_password":"أنشئ كلمة السر الجديدة",
    "Confirm_Password":"تأكيد كلمة السر",
    "Password_length_short":"طول كلمة السر قصير",
    "Confirm_Password_is_required":"تأكيد كلمة السر مطلوب",
    "both_Passwords_are_different":"كلتا كلمات السر مختلفة",
    "password_Changed_Successfully":"تم تغيير الرقم السري بنجاح",

    "service_fee_wallet":" يتم دفع رسوم الخدمة مقدمًا من خلال المحفظة",

    "rate_this_Property":"قم بتقييم العقار",
    "Already Reviewed":"تمت مراجعته بالفعل",
    "Review_submitted_successfully":"تم إرسال المراجعة بنجاح",
    "Profile_Updated_Successfully":"تم تحديث الملف الشخصي بنجاح",

    "listing": "قائمة",
    "discover-tranquility" : "اكتشف الهدوء والرفاهية في المنتجعات."


  };









//old translation
/*
  static const Map<String,dynamic> ku = {

    "service_fee_wallet":" نرخی خزمەتگوزاری پێشوەختە لە ڕێگەی ژمارە موبایل یان جزدانەوە دەدرێت",
    "kindly_transfer_the_service_fee_to_one_of_the_below_numbers_through_the_provide_wallets_for_swift_booking_approval": "تکایە کرێی خزمەتگوزارییەکە بنێرە بۆ یەکێک لەم ژمارانەی خوارەوە  بۆ پەسەندکردنی خێرا بۆ حجزکردن",
    "privacy_policy": "سياسەتی پاراستنی نه ێنی",
    "explore": "lêkolîn",
    "new_reviews": "پێداچوونەوەکان",

    "property_name": "ناوی هاوسیند",
    "property_description": "%@شێوازی هاوسیند",
    "review_text": "نوسینەوەی نوێ",
    "discover_book_and_experience_daily_stays_effortlessly": "بیدۆز ەر ەوە، حجز بکە و ئەزموون ی مانەوەی ڕۆژان ە بەبێ ماندووبوون بکە",
    "travel_made_simple_moments_made_special_find_unique_stays_with_us": "سەفەرکردن ئاسان کرا، ساتەکان تایبەت کرا لەگەڵ ئێمە شوێنی مانەوەی ناوازە بدۆزەرەوە",
    "make_your_trip_unforgettable_Smooth_stays_and_great_memories!": "بە مانەوەت لە سروشتی ئارام و یادگاری نایاب گەشتەکەت بکە بە یادگاریەكی لەبیرنەکراو ",
    "experience_Kurdistans_charm_in_our_cozy_homes_!": "كە پڕە لە میوانداری گەرم و شانازی كەلتوری",
    "filled_with_warm_hospitality_and_cultural_pride_Your_stay_promises_magic_and_true_beauty": "كە پڕە لە میوانداری گەرم و شانازی كەلتوری  بەڵێنی سحر و جوانی ڕاستەقینەت پێدەدەین بە مانەوەت لە ناو ماڵە ئارامەكانمام. ",
    "feel_at_home_in_any_place": "هەست بە بوون لە ماڵەوە بکە لە هەر شوێنێک",
    "we_got_a_cozy_place_waiting_for_you_no_matter_where_your_adventures_take_you": "ئێمە چاوەڕێی ئێوەین لە شوێنە ئارامەكانمان، گرنگ نییە هەنگاو و ئارەزوەكانت  بەرەو كوێت ببەن , لە هەموو شوێنێك باشترینەكانمان بۆ ئامادە كردوون",
    "next": "دواتر",
    "search": "گەڕان",
    "filter": "فلتەر",
    "tourist_places": "شوێنی گەشتیاری",
    "register": "تۆمارکردن",
    "your_destination?": "؟ شوێنی مەبەستت",
    "choose_a_property": "موڵکێک هەڵبژێرە",
    "daily": "ڕۆژانە",
    "weekly": "هەفتانە",
    "monthly": "مانگانە",
    "january": "کانونی دووەم",
    "February": "فبراير",
    "march": "ئازار",
    "april": "نیسان",
    "may": "ئایار",
    "june": "حوزەیران",
    "july": "تەموز",
    "august": "ئاب",
    "september": "ئەیلول",
    "october": "تشرینی یەکەم",
    "november": "تشرینی دووەم",
    "december": "کانوونی یەکەم",
    "price": "نرخ",
    "offers": "داشکاندن",
    "rating": "پۆلێنکردن",
    "description": "پوختە",
    "reviews": "پێداچوونەوەکان",
    "map": "نەخشە",
    "select": "هەڵبژێرە",
    "book": "حجز بکە",
    "for_singles": "بۆ سینگڵەکان",
    "for_families": "بۆ خێزانەکان",
    "check_in_date": "بەرواری هاتنە ژوورەوە",
    "check_out_date": "بەرواری دەرچوون",
    "facilities": "وردەکاریەکان",
    "living_Room": "ژووری دانیشتن",
    "bed_Room": "ژووری نووستن",
    "kitchen": "چێشتخانە",
    "pool": "مەلەوانگە",
    "washroom": "گەرماو",
    "overview": "کورتە",
    "have_a_question?": "پرسیارێکتان هەیە؟",
    "ask_the_host": "لە خاوەن بپرسە",
    "book_Now": "ئێستا حجز بکە",
    "what_did_property_guests_say": "میوانانی موڵک چییان گوتیە",
    "rate_us!": "هەڵسەنگاندنمان بۆ بکەن!",
    "approximate_location": "شوێنی نزیکەیی",
    "view_on_map": "بینین لەسەر نەخشە",
    "property_terms": "مەرجەکانی خاوەن",
    "cancelation_and_postponement_policy": "یاساکانی هەڵوەشاندنەوە و دواخستنی",
    "home": "سەرەکی",
    "wishlist": "دڵخوازەکان",
    "messages": "نامەکان",
    "hello": "سڵاو",
    "profile": "هەژمار",
    "booking": "حجزکردن",
    "notifications": "ئاگادارکردنەوەکان",
    "change_language": "گۆڕینی زمان",
    "fAQ": "پرسیارە بەردەوامەکان",
    "terms_of_use": "مەرجەکانی بەکارهێنان",
    "contact_us": "پەیوەندیمان پێوەبکە",
    "logout": "چوونە دەرەوە",
    "Begin_Your_Hosting_Journey_Do": "گەشتی میوانکردن دەست پێ بکەئایا خانۆی گەشتیاری ،ڤیلا، مەزرەعە مۆتێل، کەرەڤان، هۆتێل تان هەیە؟لەگەڵ ئێمە میوانداری بکە، داهاتی زیادە بەدەستبهێنە ",











    "browse_pics_to_upload": "گەڕان بەدوای وێنەکان",

    "property_details": " وردەکارییەکانی موڵکەکەت",

    "posted_Properties": "موڵکەکانی پۆ ستکراو ",
    "total_bookings": "کۆی گشت ی حجزەکان",
    "total_earning": "کۆی داهات",
    "average_rating": "تێکڕای ه ەڵسەنگاندن",
    "enter_Property_Name": "ناو ی موڵکەکە دابن ێ",
    "what_makes_your_property_unique?": "چی وايکردووە موڵکەکەت تاي بەت بێت ؟",
    "describe_your_property": "وەسفی موڵکت بکە",
    "area_of_your_property": "بە م ەتر) ڕووبەری موڵکەکەت)",
    "living_room": "هۆڵ",
    "bed_Rooms": "ژوور ی نوستن",
    "describe_your_Bed_Rooms": "باسی ژووری نوستنەکانت بکە",
    "describe_your_Kitchen": "باسی چێ شتخانەکەت بک ە",
    "describe_your_Washroom": "باسی گەرماوەکان بکە",
    "describe_your_pool": "باسی مەلە وانگە بک ە",
    "images": "وێ نە",
    "add_photos": "وێ نە ز ياد بکە",
    "landlord_ID": "ناسنامەی خاوە ن م ۆڵک ",
    "where_is_located": "لە کو ێيە",
    "full_address": "ناونيشان ی تەواو",
    "latidude_and_longidude": "پان ی و درێژ ی",
    "property_Type": "جۆری موڵک",
    "rent_type": "جۆری کرێ",
    "tenant_type": "جۆری کرێ چی",
    "price_(IQD)": "نرخ (IQD)",
    "phone_no": "ژمارەی تەلەفۆن",
    "failed_to_add_property": "سەرکەوتوو نەبوی لە زيادکردنی موڵک",
    "sign_up": "خۆت تۆمار بک ە",
    "sign_in": "چوونە ژوورەوە",
    "login_to_your_account": "تسجيل الدخول إلى حسابك",
    "email": "بريد إلكتروني",
    "password": "كلمة المرور",
    "forget_your_password?": "نسيت كلمة المرور؟",
    "email_is_required": "البريد الالكتروني مطلوب",
    "wrong_password(when_entering_wrong_password_errors)": "كلمة مرور خاطئة",
    "do_not_have_an_account?": "لا تملك حساب؟",
    "select_which_contact_details_should_we_use_to_reset_your_password": "اختر تفاصيل الاتصال التي ينبغي أن نستخدمها لإعادة تعيين كلمة المرور الخاصة بك",
    "via_Email": "عبر البريد الالكتروني",
    "via_SMS": "عبر الرسالة",
    "oTP_verification": "التحقق من OTP ",
    "code_has_been_sent_to:": "کۆدەکە نێردرا بۆ:",
    "verify": "تحقق من",
    "resend": "إعادة إرسال",
    "create_new_account": "انشاء حساب جديد",
    "full_Name": "الاسم الكامل",
    "i_agree_with_terms_and_privacy": "أوافق على الشروط والخصوصية",
    "already_have_an_account": "هل لديك حساب",




    "settings": "ڕێکخستن",
    "more": "زياتر",
    "full_name_is_required": "ناوی تەواوت پ ێويستە ",
    "password_is_required": "وشەی نهێ نی پێ ويست ە",
    "please_accept_the_terms_and_conditions": "تکايە مە رج و ڕێساکان قبوڵ بکەن",
    "oTP_sent_successfully": " OTP بە س ەرک ەوتوويی نێردرا بۆ ئیمێلت",
    "privacy policy": "سياسەتی پاراستنی نه ێنی",
    "tourist_Places": "شوێنی گەشتیاری",
    "my_Properties": "موڵکەکانی من",
    "hello_Landlord": "سڵاو خاوەن مۆڵک",
    "host_with_us": "لەگەڵ ئێمە میوانداری بکە",
    "travel_to_cities": "گەشت بۆ شارەکان",
    "search_by_Cities": "گەڕان بەپێی شار",
    "quick_contact": "پەیوەندی خێرا",
    "chat": "نامە",
    "email_us": "ئیمەیڵمان بۆ بنێرە",
    "enter_your_message_here": "لێرەدا نامەکەت بنووسە",
    "send": "ناردن",
    "name_is_required": "ناو پێویستە",
    "emalid email is required": "ئیمەیڵی دروست پێویستە",
    "message is required": "نامە پێویستە",
    "query_sent_successfully": "پرسیارەکە بە سەرکەوتوویی نێردراوە.",
    "payment_Successful ": "پارەدان سەرکەوتوو بوو",
    "booking_Successful": "حجزکردن سەرکەوتوو بوو",
    "past": "ڕابردوو",
    "upcoming": "لە داهاتوودا",
    "booking_id": "ناسنامەت بۆ حجزکردن",
    "pending": "لە چاوەڕوانیدا",
    "update": "نوێکردنەوە",
    "iD_Proof": "سەلماندنی ناسنامە",
    "favourites": "دڵخوازەکان",
    "sq._feet": "پێی دووجا",
    "submit": "ناردن ",
    "wrong_Password": "پاسۆردەکەت هەڵەیە",
    "login_Successful": "چوونەژوورەوە سەرکەوتوو بوو",
    "post_Property": "موڵکێک پۆست بکە",
    "begin_Your_Hosting_Journey": "گەشتی میوانداریکردنت دەست پێ بکە",
    "add_Property_Details": "وردەکارییەکانی موڵکەکەت زیاد بکە",
    "in_meters": "بە مەتر",
    "select_number_of_available_rooms": "ژمارەی ژوورەکانی بەردەست هەڵبژێرە",
    "describe_Your_Living_rooms": "باسی ژووری میوانەکانت بکە",
    "select_number_of_Kitchen": "ژمارەی چێشتخانەکان هەڵبژێرە",
    "select_the_tentant_type": "جۆری کرێچی هەڵبژێرە",
    "smoking_type": "جۆری جگەرەکێشان",
    "select_Smoking_type": "جۆری جگەرەکێشان هەڵبژێرە",
    "select_the_smoking_type": "جۆری جگەرەکێشان هەڵبژێرە",
    "add_manually_The_Terms_and_Conditions": " مەرج و ڕێساکان تۆ زیاد بکە",
    "add_manually_Cancellation_Policy": "سیاسەتی هەڵوەشاندنەوە تۆ زیاد بکە",
    "select_the_terms_and_conditions_or_type_it": "مەرج و ڕێساکان هەڵبژێرە یان بینووسە",
    "failed_to_add_business": " شکستت هێنا لە زیادکردنی موڵکەکە",
    "last_seen_on": "دوایین جار بینراوە لە",
    "type_Something": "شتێک بنووسە",
    "mark_unavailable": " بەردەست نییە ئێستا",
    "update_Price": "گۆڕینی نرخ",
    "property_price_updated_successfully": "نرخی موڵک بە سەرکەوتوویی گۆڕدرا",
    "property_price_is_required": "نرخی موڵک پێویستە",





    "app_title": "پشتیوانم",
    "experience_Kurdistan's_charm_in_our_cozy_homes_!": "كە پڕە لە میوانداری گەرم و شانازی كەلتوری",
    "filled_with_warm_hospitality_and_cultural_pride_Your_stay_promises_magic_and_true_beauty!": "كە پڕە لە میوانداری گەرم و شانازی كەلتوری  بەڵێنی سحر و جوانی ڕاستەقینەت پێدەدەین بە مانەوەت لە ناو ماڵە ئارامەكانمام. ",
    "feel_at_home_in_any_place.": "هەست بە بوون لە ماڵەوە بکە لە هەر شوێنێک",
    "we've_got_a_cozy_place_waiting_for_you,_no_matter_where_your_adventures_take_you!": "ئێمە چاوەڕێی ئێوەین لە شوێنە ئارامەكانمان، گرنگ نییە هەنگاو و ئارەزوەكانت  بەرەو كوێت ببەن , لە هەموو شوێنێك باشترینەكانمان بۆ ئامادە كردوون",
    "area_of_your_property_(in meter)": "بە م ەتر) ڕووبەری موڵکەکەت)",
    "email_is_required_(when_entering_wrong_email_errors)": "البريد الالكتروني مطلوب",


    "emalid_email_is_required": "ئیمەیڵی دروست پێویستە",
    "message_is_required": "نامە پێویستە",
    "query_sent_successfully.": "پرسیارەکە بە سەرکەوتوویی نێردراوە.",

    "amount_Paid": "بڕی دراو",
    "booking_date": "بەرواری حجزکردن",
    "resort_Houses": "خانووی گەشتیاری",
    "caraven_&_Kepr": "کەرەڤان و کەپر",
    "farm_House": "مەزرەعە",
    "motel_&_Private_Flats": "موتێل و شوقەی تایبەت",
    "hotel": "هۆتێل",
    "booking_Details_not_found": "وردەکاری حجزکردن نەدۆزرایەوە",
    "apartment": "شوقە",
    "night": "شەو",
    "unit_code": "کۆدی یەکە",
    "for_Singles_": "بۆ سینگڵەکان",
    "choose_language": "زمان هەڵبژێرە",
    "write_Review": "سەرنجەکانتان بنووسن",
    "describe_Your_Experience": "ئەزموونی خۆت باس بکە",
    "post": "ناردن",
    "checkout": "دەرچوون",
    "select_number_of_Pools":  "گەڕان بەدوای وێنەکان ",
    "reservation_Details": "وردەکاری حجزکردن",
    "sub_Total": "پێش- کۆی گشتی ",
    "service_Fee": "کرێی خزمەتگوزاری",
    "total": "کۆی گشتی",
    "payment_method": "شێوازی پارەدان",
    "cash": "پارەی کاش",
    "wallets": "جزدان",
    "payment_Procedure": "ڕێکارەکانی پارەدان",
    "book_Property": "موڵکێک حجز بکە",
    "property_Booked,_Please_wait_for_admin_approval": "موڵکەکە حجز کرا، تکایە چاوەڕێی ڕەزامەندی ئەدمین بن",
    "booking_Done": "حجزکردن ئەنجام درا",
    "booking_sent_for_approval_successfully": "حجزکردن نێردرا بۆ پەسەندکردن",
    "your_payment_for_booking_property_is_successfully_done._Please_wait_for_booking_confirmation.": "پارەدانەکەت بۆ حجزکردنی موڵک بە سەرکەوتوویی ئەنجامدرا. تکایە چاوەڕێی پشتڕاستکردنەوەی حجزکردن بن.",
    "your_property_booking_is_successfully_confirmed_by_administration.": "حجزکردنەکە بە سەرکەوتوویی لەلایەن ئەدمینەوە پشتڕاست کراوە",
    "we're_here_to_help you_with_anything_and_everything_on_Gasht": "ئێمە لێرەین بۆ ئەوەی یارمەتیت بدەین لە هەر شتێک و هەموو شتێک لەسەر Gasht",
    "by_your_use_of_this_app,_you_confirm_your_acceptance_and_it_would_be_accepted_as_would_a_written agreement_would_a_written_agreement": "بە بەکارهێنانی ئەم ئەپە، قبوڵکردنەکەت پشتڕاست دەکەیتەوە و وەرگیرا وەک چۆن ڕێککەوتنێکی نووسراو ڕێککەوتنێکی نووسراو وەردەگیرێت",
    "arabic": "عەرەبی",
    "kurdish": "کوردی",
    "select_Number_of_washroom": "ژمارەی گەرماوەکان هەڵبژێرە",
    "booking_Detail": "وردەکاری حجزکردن",
    "booked": "حجز کرا",
    "booking_Date": "بەرواری حجزکردن",
    "booking_ID ": "ناسنامەی حجزکردن",
    "daily_quote": "وتەی ڕۆژانە",
    "oK": "باشە",


    "otp_verified":"کۆدی OTP بە سەرکەوتوویی پشتڕاستکرایەوە",
    "Create_Password":"پاسوۆردێک دروستبکە",
    "Create_your_new_password":"وشەی نهێنی نوێت دروست بکە",
    "Confirm_Password":"وشەی نهێنی پشتڕاست بکەرەوە",
    "Password_length_short":"پاسوۆردەکە کورتە",
    "Confirm_Password_is_required":"پاسۆرد پشتڕاستکردنەوە پێویستە  ",
    "both_Passwords_are_different":"هەردوو پاسۆردەکە جیاوازن",
    "password_Changed_Successfully":"پاسۆرد بە سەرکەوتوویی گۆڕدرا",




















  }


  ;
static const Map<String,dynamic> en ={
  "kindly_transfer_the_service_fee_to_one_of_the_below_numbers_through_the_provide_wallets_for_swift_booking_approval": "Kindly transfer the service fee to one of the below numbers through the provide wallets for swift booking approval",
  "app_title": "My App",
  "explore": "Explore",
  "property_name": "Property Name",
  "property_description": "Property Description%@",
  "review_text": "Review Text",
  "discover_book_and_experience_daily_stays_effortlessly": "Discover, book, and experience daily stays effortlessly.",
  "travel_made_simple_moments_made_special_find_unique_stays_with_us": "Travel made simple moments made special find unique stays with us.",
  "make_your_trip_unforgettable_Smooth_stays_and_great_memories!": "Make your trip unforgettable Smooth stays and great memories!",
  "experience_Kurdistans_charm_in_our_cozy_homes_!": "Experience Kurdistan's charm in our cozy homes !",
  "filled_with_warm_hospitality_and_cultural_pride_Your_stay_promises_magic_and_true_beauty": "Filled with warm hospitality and cultural pride. Your stay promises magic and true beauty!",
  "feel_at_home_in_any_place": "Feel at home in any place.",
  "we_got_a_cozy_place_waiting_for_you_no_matter_where_your_adventures_take_you": "We've got a cozy place waiting for you, no matter where your adventures take you!",
  "next": "NEXT",
  "search": "Search",
  "filter": "Filter",
  "tourist_places": "Tourist places",
  "register": "Register",
  "your_destination?": "Your destination?",
  "choose_a_property": "Choose a property",
  "daily": "Daily",
  "weekly": "Weekly",
  "monthly": "Monthly",
  "january": "January",
  "february": "February",
  "march": "March",
  "april": "April",
  "may": "May",
  "june": "June",
  "july": "July",
  "august": "August",
  "september": "September",
  "october": "October",
  "november": "November",
  "december": "December",
  "price": "Price",
  "offers": "Offers",
  "rating": "Rating",
  "description": "Description",
  "reviews ": "Reviews ",
  "new_reviews":"Reviews",
  "map": "Map",
  "select": "Select",
  "book": "Book",
  "for_singles": "For singles",
  "for_families": "For families",
  "check_in_date": "Check-in date",
  "check_out_date": "Check-out date",
  "facilities": "Facilities",
  "living_Room": "Living Room",
  "bed_Room": "Bed Room ",
  "kitchen": "Kitchen",
  "pool": "Pool",
  "washroom": "Washroom",
  "overview": "Overview",
  "have_a_question?": "Have a question?",
  "ask_the_host": "Ask the host",
  "book_Now": "Book Now",
  "what_did_property_guests_say": "What did property guests say",
  "rate_us!": "Rate us!",
  "approximate_location": "Approximate location",
  "view_on_map": "View on map",
  "property_terms": "Property Terms",
  "new_terms": "Property Terms",
  "cancelation_and_postponement_policy": "Cancellation and postponement policy",
  "home": "Home",
  "wishlist": "Wishlist",
  "messages": "Messages",
  "more": "More",
  "hello": "Hello",
  "profile": "Profile",
  "booking": "Booking",
  "notifications": "Notifications",
  "change_language": "Change Language",
  "fAQ": "FAQ",
  "terms_of_use": "Terms of use",
  "contact_us": "Contact us",
  "logout": "Logout",
  "Begin_Your_Hosting_Journey_Do": "Begin Your Hosting Journey Do you have Tourist house, Villa, Farmhouse Motel, Caravans, Hotel Host with us, earn extra income",

  "posted_Properties": "Posted Properties",
  "total_bookings": "Total bookings",
  "total_earning": "Total earning",
  "average_rating": "Average rating",
  "enter_Property_Name": "Enter Property Name",
  "what_makes_your_property_unique?": "What makes your property unique?",
  "describe_your_property": "Describe your property",
  "area_of_your_property": "Area of your property (in meter)",
  "living_room": "living room",
  "bed_Rooms": "Bed Rooms",
  "describe_your_Bed_Rooms": "Describe your Bed Rooms",
  "describe_your_Kitchen": "Describe your Kitchen",
  "describe_your_Washroom": "Describe your Washroom",
  "describe_your_pool": "Describe your pool",
  "images": "Images",
  "add_photos": "Add photos",
  "landlord_ID": "Landlord ID",
  "where_is_located": "Where is located",
  "full_address": "full address",
  "latidude_and_longidude": "Latitude and Longitude",
  "property_Type": "Property Type",
  "rent_type": "Rent type",
  "tenant_type": "Tenant type",
  "price_(IQD)": "Price (IQD)",
  "phone_no": "Phone no",
  "failed_to_add_property": "Failed to add property",
  "sign_up": "Sign up",
  "sign_in": "Sign in",
  "login_to_your_account":"Login to your account",
  "email": "Email",
  "password": "Password",
  "forget_your_password?": "Forget your password?",
  "email_is_required_(when_entering_wrong_email_errors)": "Email is required (when entering wrong email errors)",
  "wrong_password(when_entering_wrong_password_errors)": "Wrong password (when entering wrong Password errors)",
  "do_not_have_an_account?": "Do not have an account?",
  "select_which_contact_details_should_we_use_to_reset_your_password": "Select which contact details should we use to reset your password",
  "via_Email": "Via Email",
  "via_SMS": "Via SMS",
  "oTP_verification": "OTP verification",
  "code_has_been_sent_to:": "Code has been sent to:",
  "verify": "Verify",
  "resend": "Resend",
  "create_new_account": "Create new account",
  "full_Name": "Full Name",
  "i_agree_with_terms_and_privacy": "I agree with terms and privacy",
  "already_have_an_account": "Already have an account",

  "settings": "Setting",
  "full_name_is_required": "Full name is required",
  "email_is_required":"Email is required",
  "valid_email_is_required": "Valid email is required",
  "password_is_required": "Password is required",
  "please_accept_the_terms_and_conditions": "Please accept the terms and conditions",
  "oTP_sent_successfully": "OTP sent successfully",
  "privacy_policy": "Privacy policy",
  "tourist_Places": "Tourist Places",
  "my_Properties": "My Properties",
  "hello_Landlord": "Hello Landlord",
  "host_with_us": "Host with us",
  "travel_to_cities": "Travel to cities",
  "search_by_Cities": "Search by Cities",
  "quick_contact": "Quick contact",
  "chat": "Chat",
  "email_us": "Email us",
  "enter_your_message_here": "Enter your message here.....",
  "send": "Send",
  "name_is_required": "Name is required",
  "email is required": "Email is required",
  "emalid email is required": "Valid email is required",
  "message_is_required": "Message is required",
  "query_sent_successfully": "Query sent successfully.",
  "payment_Successful": "Payment Successful ",
  "booking_Successful": "Booking Successful",
  "Past": "Past",
  "upcoming": "Upcoming",
  "booking_id": "Booking id",
  "pending": "Pending",
  "update": "Update",
  "iD_Proof": "ID Proof",
  "favourites": "Favourites",
  "sq._feet": "sq. feet",
  "submit": "Submit",
  "wrong_Password": "Wrong Password",
  "login_Successful": "Login Successful",
  "post_Property": "Post Property",
  "begin_Your_Hosting_Journey": "Begin Your Hosting Journey",
  "add_Property_Details": "Add Property Details",
  "in_meters": "In meters",
  "select_number_of_available_rooms": "Select number of available rooms",
  "describe_Your_Living_rooms": "Describe Your Living rooms",
  "select_number_of_Kitchen": "Select number of Kitchen",
  "select_number_of_Pools": "Select number of Pools",
  "browse_pics_to_upload": "Browse pics to upload",
  "property_name_is_required": "Property name is required",
  "property_Description_is_required": "Property Description is required",
  "area_of_property_is_required": "Area of property is required",
  "at_least_one_image_is_required": "At least one image is required",
  "add_Location_and_Terms": "Add Location and Terms",
  "select_city": "Select city",
  "select_the_rent_type": "Select the rent type",
  "select_the_property_type": "Select the property type",
  "select_the_tentant_type": "Select the tentant type",
  "smoking_type": "Smoking type",
  "select_Smoking_type": "Select Smoking type",
  "select_the_smoking_type": "Select the smoking type",
  "add_manually_The_Terms_and_Conditions": "Add manually The Terms and Conditions",
  "add_manually_Cancellation_Policy": "Add manually Cancellation Policy",
  "select_the_terms_and_conditions_or_type_it": "Select the terms and conditions or type it",
  "failed_to_add_business": "Failed to add business",
  "last_seen_on": "Last seen on",
  "type_Something": "Type Something",
  "mark_unavailable": "Mark unavailable",
  "update_Price": "Update Price",
  "property_price_updated_successfully": "Property price updated successfully",
  "property_price_is_required": "Property price is required",
  "property_details": "Property Details",

  "service_fee_wallet":"Service fee is to be paid in advance through wallet",


  "otp_verified":"OTP verified Successfully",
  "password_Changed_Successfully":"Password Changed Successfully",
  "both_Passwords_are_different":"Both Passwords are different",
  "Create_Password":"Create Password",
  "Confirm_Password":"Confirm Password",
  "Create_your_new_password":"Create your new password",
  "Password_length_short":"Password length is short",
  "Confirm_Password_is_required":"Confirm Password is required",
  "service_fee_advance":"Service fee is to be paid in advance through wallet",



  "experience_Kurdistan's_charm_in_our_cozy_homes_!": "Experience Kurdistan's charm in our cozy homes !",
  "filled_with_warm_hospitality_and_cultural_pride_Your_stay_promises_magic_and_true_beauty!": "Filled with warm hospitality and cultural pride. Your stay promises magic and true beauty!",
  "feel_at_home_in_any_place.": "Feel at home in any place.",
  "we've_got_a_cozy_place_waiting_for_you,_no_matter_where_your_adventures_take_you!": "We've got a cozy place waiting for you, no matter where your adventures take you!",




  "area_of_your_property_(in meter)": "Area of your property (in meter)",

  "quick_contact ": "Quick contact",
  "Chat": "Chat",
  "emalid_email_is_required": "Valid email is required",
  "query_sent_successfully.": "Query sent successfully.",
  "payment_Successful ": "Payment Successful ",

  "amount_Paid": "Amount Paid",
  "booking_date": "Booking date",
  "resort_Houses": "Resort Houses",
  "caraven_&_Kepr": "Caraven & Kepr",
  "farm_House": "Farm House",
  "motel_&_Private_Flats": "Motel & Private Flats",
  "hotel": "Hotel",
  "booking_Details_not_found": "Booking Details not found",
  "apartment": "Apartment",
  "night": "Night",
  "unit_code": "Unit code",
  "for_Singles_": "For Singles ",
  "choose_language": "Choose language",
  "write_Review": "Write Review",
  "describe_Your_Experience": "Describe Your Experience",
  "post": "Post",
  "checkout": "Checkout",
  "reservation_Details": "Reservation Details",
  "sub_Total": "Sub-Total",
  "service_Fee": "Service Fee",
  "total": "Total",
  "payment_method": "Payment method",
  "cash": "Cash",
  "wallets": "Wallets",
  "payment_Procedure": "Payment Procedure",
  "book_Property": "Book Property",
  "property_Booked_Please_wait_for_admin_approval": "Property Booked, Please wait for admin approval",
  "booking_Done": "Booking Done",
  "booking_sent_for_approval_successfully": "Booking sent for approval successfully",
  "your_payment_for_booking_property_is_successfully_done._Please_wait_for_booking_confirmation.": "Your payment for booking property is successfully done. Please wait for booking confirmation.",
  "your_property_booking_is_successfully_confirmed_by_administration.": "Your property booking is successfully confirmed by administration.",
  "we're_here_to_help you_with_anything_and_everything_on_Gasht": "We're here to help you with anything and everything  on Gasht",
  "by_your_use_of_this_app,_you_confirm_your_acceptance_and_it_would_be_accepted_as_would_a_written agreement_would_a_written_agreement": "By your use of this app, you confirm your acceptance and it would be accepted as would a written agreement would a written agreement",
  "arabic": "Arabic",
  "kurdish": "Kurdish",
  "select_Number_of_washroom": "Select Number of washroom",
  "booking_Detail": "Booking Detail",
  "booked": "Booked",
  "booking_Date": "Booking Date",
  "booking_ID ": "Booking ID ",
  "daily_quote": "Daily quote",
  "oK": "OK"

}

  ;




static const Map<String,dynamic> ar ={
  "kindly_transfer_the_service_fee_to_one_of_the_below_numbers_through_the_provide_wallets_for_swift_booking_approval": "يرجى تحويل رسوم الخدمة إلى أحد الأرقام أدناه من خلال المحافظ المخصصة للموافقة السريعة على الحجز",
  "privacy_policy": "سياسة الخصوصية",
  "app_title": "تطبيقي",
  "hello": "مرحبا",
  "explore": "يستكشف",
  "property_description": " @% وصف العقار",
  "review_text": "نص المراجعة",
  "discover_book_and_experience_daily_stays_effortlessly": "اكتشف واحجز واستمتع بتجربة الإقامات اليومية بسهول ة",
  "travel_made_simple_moments_made_special_find_unique_stays_with_us": "أصبح السفر بسيطًا، واللحظات أصبحت مميزة ابحث عن إقامات فريدة معنا",
  "make_your_trip_unforgettable_Smooth_stays_and_great_memories!": "اجعل رحلتك لا تنسى إقامات هادئة وذكريات رائعة",
  "experience_Kurdistans_charm_in_our_cozy_homes_!": "!أستمتع بسحر كردستان في منازلنا المريحة",
  "filled_with_warm_hospitality_and_cultural_pride_Your_stay_promises_magic_and_true_beauty": "المليئة بكرم الضيافة والفخر الثقافي إقامتك تبشر بالسحر والجمال الحقيقي.",
  "feel_at_home_in_any_place": "تشعر وكأنك في منزلك في أي مكان",
  "we_got_a_cozy_place_waiting_for_you_no_matter_where_your_adventures_take_you": "لدينا مكان مريح في انتظارك، بغض النظر عن المكان الذي تأخذك إليه مغامراتك!",
  "next": "التالي",
  "search": "ابحث",
  "filter": "فلتر",
  "tourist_places": "الاماكن السياحية",
  "register": "تسجیل",
  "your_destination?": "وجهتك؟",
  "choose_a_property": "اخترعقارًا",
  "daily": "يوميا",
  "weekly": "اسبوعي",
  "monthly": "شهريا",
  "january": "يناير",
  "february": "فبراير",
  "march": "مارس",
  "april": "إبريل",
  "may": "مايو",
  "june": "يونيو",
  "july": "يوليو",
  "august": "أغسطس",
  "september": "سبتمبر",
  "october": "أكتوبر",
  "november": "نوفمبر",
  "december": "ديسمبر",
  "price": "السعر",
  "offers": "العروض",
  "rating": "التقييم",
  "description": "المواصفات",
  "reviews": "المراجعات",
  "map": "خريطة",
  "select": "اختر",
  "book": "احجز",
  "new_reviews": "المراجعات",

  "for_singles": "للعزاب",
  "for_families": "للعائلات",
  "check_in_date": "تاريخ الدخول",
  "check_out_date": "تاريخ المغادرة",
  "facilities": "التفاصيل",
  "living_Room": "غرفة الجلوس",
  "bed_Room": "غرفة نوم",
  "kitchen": "المطبخ",
  "pool": "حوض السباحة",
  "washroom": "الحمام",
  "overview": "ملخص",
  "have_a_question?": "لديك سؤال؟",
  "ask_the_host": "اسأل المضيف",
  "book_Now": "احجز الآن",
  "what_did_property_guests_say": "ماذا قال ضيوف مكان الإقامة؟",
  "rate_us!": "قيمنا!",
  "approximate_location": "الموقع التقريبي",
  "view_on_map": "عرض على الخريطة",
  "property_terms": "شروط الملكية",
  "cancelation_and_postponement_policy": "سياسة الإلغاء والتأجيل",
  "home": "الرئيسية",
  "wishlist": "المفضلة",
  "messages": "الرسائل",
  "profile": "حسابك",
  "booking": "الحجز",
  "notifications": "الإشعارات",
  "change_language": "تغيير اللغة",
  "fAQ": "الأسئلة الشائعة",
  "terms_of_use": "شروط الاستخدام",
  "contact_us": "اتصل بنا",
  "logout": "تسجيل خروج",
  "Begin_Your_Hosting_Journey_Do": "بدأ رحلة الاستضافة الخاصة بك هل لديك بيت سياحي، فيلا، مزرعةموتيل، كرفان، فندق؟استضف معنا واحصل على دخل إضافي",





  "property_name": "اسم الملكية",
  "posted_Properties": "االمالك المنشورة",
  "total_bookings": "إجمالي الحجوزات",
  "total_earning": "األرباح الكلية",
  "average_rating": "معدل تقييم",
  "enter_Property_Name": "أدخل اسم العقار",
  "what_makes_your_property_unique?": "ما الذي يجعل ملكك فريدة من نوعها؟",
  "describe_your_property": "قم بوصف ملكك",
  "area_of_your_property": "بالمتر) مساحة عقارك)",
  "living_room": "غرفة المعيشة",
  "bed_Rooms": "غرف النوم",
  "describe_your_Bed_Rooms": "قم بوصف غرف النوم",
  "describe_your_Kitchen": "قم بوصف مطبخك ",
  "describe_your_Washroom": "قم بوصف الحمام",
  "describe_your_pool": "وصف حوض السباحة",
  "images": "الصور",
  "add_photos": "أضف صور",
  "landlord_ID": "هوية المالك",
  "where_is_located": "اين يقع",
  "full_address": "العنوان الكامل",
  "latidude_and_longidude": "خط العرض وخط الطول",
  "property_Type": "نوع الملكية",
  "rent_type": "نوع اإليجار",
  "tenant_type": "نوع المستأجر",
  "price_(IQD)": "السعر(IQD)",
  "phone_no": "رقم الهاتف",
  "failed_to_add_property": "فشل في إضافة الملك",
  "sign_up": "قم بالتسجيل",
  "sign_in": "تسجيل الدخول",
  "login_to_your_account": "بچۆرە ناو هەژمارەكەت",
  "email": "ئیمەیڵ",
  "password": "وشەی نهێنی",
  "forget_your_password?": "وشەی نهێنی خۆت لەبیکردووە؟",
  "email_is_required": "ئیمەیڵ پێویستە",
  "wrong_password": "وشەی نهێنی هەڵەیە",
  "do_not_have_an_account?": "هەژمارت نییە؟",
  "select_which_contact_details_should_we_use_to_reset_your_password": "ئەم ڕێگایەی خوارەوە هەڵبژێرە بۆ گوڕینی وشەی نهێنیەکەت",
  "via_Email": "لە ڕێگەی ئیمەیڵەوە",
  "via_SMS": "لە ڕێگەی نامە",
  "oTP_verification": "پشتڕاستکردنەوەی OTP",
  "code_has_been_sent_to:": "کۆدەکە نێردرا بۆ:",
  "verify": "پشتڕاست بکەرەوە",
  "resend": "دووبارە ناردنەوە",
  "create_new_account": "ئەکاونتی نوێ دروست بکە",
  "full_Name": "ناوى تەواو",
  "i_agree_with_terms_and_privacy": "من لەگەڵ مەرجەکان و تایبەتمەندییەکانم",
  "already_have_an_account": "پێشتر خۆت تۆمار کردووە",

  "browse_pics_to_upload": "تصفح الصور للتحميل",

  "settings": "ضبط",
  "more": "المزيد",
  "full_name_is_required": "االسم الكامل مطلوب",
  "password_is_required": "مطلوب كلمة المرور",
  "please_accept_the_terms_and_conditions": "يرجى قبول الشروط واألحكام",
  "oTP_sent_successfully": "تم إرسال OTP بنجاح ",
  "privacy policy": "سياسة الخصوصية",
  "tourist_Places": "أماكن سياحية",
  "my_Properties": "ممتلكاتي",
  "hello_Landlord": "مرحبا المالك",
  "host_with_us": "استضیف معنا",
  "travel_to_cities": "السفر إلى المدن",
  "search_by_Cities": "البحث حسب المدن",
  "quick_contact": "الاتصال السريع",
  "chat": "محادثة",
  "email_us": "راسلنا عبر البريد الإلكتروني",
  "enter_your_message_here": "أدخل رسالتك هنا",
  "send": "إرسال",
  "name_is_required": "الاسم مطلوب",
  "message_is_required": "الرسالة مطلوبة",
  "query_sent_successfully": "تم إرسال الاستفسار بنجاح.",
  "payment_Successful ": "تم الدفع بنجاح",
  "booking_Successful": "تم الحجز بنجاح",
  "past": "الماضي",
  "upcoming": "القادمة",
  "booking_id": "معرف الحجز",
  "pending": "قيد الانتظار",
  "update": "تحديث",
  "iD_Proof": "إثبات الهوية",
  "favourites": "المفضلة",
  "sq._feet": "قدم مربع",
  "submit": "إرسال",
  "wrong_Password": "كلمة المرور خاطئة",
  "login_Successful": "تم تسجيل الدخول بنجاح",
  "post_Property": "نشر عقار",
  "begin_Your_Hosting_Journey": "ابدأ رحلتك في الاستضافة",
  "add_Property_Details": "إضافة تفاصيل العقار",
  "in_meters": "بالمتر",
  "select_number_of_available_rooms": "اختر عدد الغرف المتاحة",
  "describe_Your_Living_rooms": "وصف غرف المعيشة الخاصة بك",
  "select_number_of_Kitchen": "اختر عدد المطابخ",
  "select_the_tentant_type": "حدد نوع المستأجر",
  "smoking_type": "نوع التدخين",
  "select_Smoking_type": "اختر نوع التدخين",
  "select_the_smoking_type": "اختر نوع التدخين",
  "add_manually_The_Terms_and_Conditions": "أضف الشروط والأحكام يدويًا",
  "add_manually_Cancellation_Policy": "أضف سياسة الإلغاء يدويًا",
  "select_the_terms_and_conditions_or_type_it": "حدد الشروط والأحكام أو اكتبها",
  "failed_to_add_business": "لقد فشلت في إضافة العقار",
  "last_seen_on": "شوهد آخر مرة في",
  "type_Something": "اكتب شيئا",
  "mark_unavailable": "وضع علامة غير متاح حاليا",
  "update_Price": "تحديث السعر",
  "property_price_updated_successfully": "تم تحديث سعر العقار بنجاح",
  "property_price_is_required": "مطلوب سعر العقار",

  "property_details": "إضافة تفاصيل",



  "experience_Kurdistan's_charm_in_our_cozy_homes_!": "!أستمتع بسحر كردستان في منازلنا المريحة",
  "filled_with_warm_hospitality_and_cultural_pride_Your_stay_promises_magic_and_true_beauty!": "المليئة بكرم الضيافة والفخر الثقافي إقامتك تبشر بالسحر والجمال الحقيقي.",
  "feel_at_home_in_any_place.": "تشعر وكأنك في منزلك في أي مكان",
  "we've_got_a_cozy_place_waiting_for_you,_no_matter_where_your_adventures_take_you!": "لدينا مكان مريح في انتظارك، بغض النظر عن المكان الذي تأخذك إليه مغامراتك!",


  "email_is_required_(when_entering_wrong_email_errors)": "ئیمەیڵ پێویستە",
  "wrong_password(when_entering_wrong_password_errors)": "وشەی نهێنی هەڵەیە",

  "quick_contact ": "الاتصال السريع",
  "emalid_email_is_required": "مطلوب البريد الإلكتروني الصحيح",
  "query_sent_successfully.": "تم إرسال الاستفسار بنجاح.",

  "amount_Paid": "المبلغ المدفوع",
  "booking_date": "تاريخ الحجز",
  "resort_Houses": "بيوت السياحية",
  "caraven_&_Kepr": "كرفان و کبر",
  "farm_House": "مزرعة",
  "motel_&_Private_Flats": "موتيل وشقق خاصة",
  "hotel": "فندق",
  "booking_Details_not_found": "لم يتم العثور على تفاصيل الحجز",
  "apartment": "شقة",
  "night": "ليلة",
  "unit_code": "كود الوحدة",
  "for_Singles_": "للعزاب",
  "choose_language": "اختر اللغة",
  "write_Review": "اكتب ملاحضاتك",
  "describe_Your_Experience": "قم بوصف تجربتك",
  "post": "انشر",
  "checkout": "الخروج",
  "select_number_of_Pools":  "تصفح الصور للتحميل",
  "reservation_Details": "تفاصيل الحجز",
  "sub_Total": "المجموع الفرعي",
  "service_Fee": "رسوم الخدمة",
  "total": "المجموع",
  "payment_method": "طريقة الدفع",
  "cash": "نقد",
  "wallets": "محفظة",
  "payment_Procedure": "إجراءات الدفع",
  "book_Property": "احجز عقارًا",
  "property_Booked,_Please_wait_for_admin_approval": "تم حجز العقار، برجاء انتظار موافقة الادمن",
  "booking_Done": "تم الحجز",
  "booking_sent_for_approval_successfully": "تم إرسال الحجز للموافقة عليه",
  "your_payment_for_booking_property_is_successfully_done._Please_wait_for_booking_confirmation.": "تم الدفع لحجز العقار بنجاح. يرجى الانتظار لتأكيد الحجز.",
  "your_property_booking_is_successfully_confirmed_by_administration.": "تم تأكيد حجز مكان الإقامة الخاص بك بنجاح من قبل الإدمن",
  "we're_here_to_help you_with_anything_and_everything_on_Gasht": "نحن هنا لمساعدتك في أي شيء وكل شيء في Gasht",
  "by_your_use_of_this_app,_you_confirm_your_acceptance_and_it_would_be_accepted_as_would_a_written agreement_would_a_written_agreement": "باستخدامك لهذا التطبيق، فإنك تؤكد موافقتك وسيتم قبوله كما هو الحال مع الاتفاقية المكتوبة",
  "arabic": "عربي",
  "kurdish": "كردي",
  "select_Number_of_washroom": "حدد عدد الحمامات",
  "booking_Detail": "تفاصيل الحجز",
  "booked": "حجزت",
  "booking_Date": "تاريخ الحجز",
  "booking_ID ": "معرف الحجز",
  "daily_quote": "الاقتباس اليومي",
  "oK": "موافق",

  "otp_verified":"تم التحقق من کلمة مرورOTP بنجاح",
  "Create_Password":"پاسوۆردێک دروستبکە",
  "Create_your_new_password":"وشەی نهێنی نوێت دروست بکە",
  "Confirm_Password":"وشەی نهێنی پشتڕاست بکەرەوە",
  "Password_length_short":"طول كلمة المرور قصير",
  "Confirm_Password_is_required":"تأكيد كلمة المرور مطلوب",
  "both_Passwords_are_different":"كلتا كلمات المرور مختلفة",
  "password_Changed_Successfully":"تم تغيير الرقم السري بنجاح",

  "service_fee_wallet":" يتم دفع رسوم الخدمة مقدمًا من خلال المحفظة",


};

*/




static const Map<String, Map<String,dynamic>> mapLocales = {"fa": ku, "en": en, "ar": ar};
}
